
name: "Control"
slug: "Control"
description: "Control add-on for Home Energy Management System (HEMS)"
image: "rueda1208/Control"
version: "1.0.0"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
init: false
startup: services
host_network: false
homeassistant_api: true
environment:
  TZ: America/Montreal