
name: "Controller"
slug: "HEMS controller"
description: "Controller add-on for Home Energy Management System (HEMS)"
image: "rueda1208/controller"
version: "latest"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
init: false
startup: services
host_network: false
homeassistant_api: true
environment:
  TZ: America/Montreal