heat_pump_performance_specs:
  cooling:
    COP_points:
      a:
        outdoor_dry_bulb_F: 95
        outdoor_dry_bulb_C: 35
        indoor_dry_bulb_F: 80
        indoor_dry_bulb_C: 27
        min: 3.74
        rated: 3.22
        max: 3.04
      b:
        outdoor_dry_bulb_F: 82
        outdoor_dry_bulb_C: 28
        indoor_dry_bulb_F: 80
        indoor_dry_bulb_C: 27
        min: 7.31
        rated: null
        max: 4.34
  heating:
    COP_points:
      a:
        outdoor_dry_bulb_F: 47
        outdoor_dry_bulb_C: 8
        indoor_dry_bulb_F: 70
        indoor_dry_bulb_C: 21
        min: 3.51
        rated: 3.04
        max: 3.21
      b:
        outdoor_dry_bulb_F: 17
        outdoor_dry_bulb_C: -8
        indoor_dry_bulb_F: 70
        indoor_dry_bulb_C: 21
        min: 2.06
        rated: 2.57
        max: 2.49
      c:
        outdoor_dry_bulb_F: 5
        outdoor_dry_bulb_C: -15
        indoor_dry_bulb_F: 70
        indoor_dry_bulb_C: 21
        min: 1.8
        rated: 2.07
        max: 2.18

hvac_systems: