
name: "Controller"
slug: "hems_controller"
description: "Expert System-Based Controller"
image: "rueda1208/controller"
version: "latest"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
init: false
startup: services
host_network: false
homeassistant_api: true
environment:
  LOGLEVEL: INFO
  TZ: America/Montreal