name: "Controller"
slug: "controller"
description: "Expert System-Based Controller"
version: "1.1.4"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
init: false
startup: services
homeassistant_api: true

map:
  - type: share # This maps Host: /share -> Container: /share
    read_only: false

environment:
  LOGLEVEL: INFO
  TZ: America/Montreal
options:
  heat_pump_enabled: true
  hems_api_base_url: "http://hems.hydroquebec.lab:8500"
  building_id: "HEMSXX"
  environment_sensor_id: "climate.heat_pump"
schema:
  heat_pump_enabled: bool
  hems_api_base_url: str
  building_id: str
  environment_sensor_id: str
