
name: "Controller"
slug: "hems_controller"
description: "Expert System-Based Controller"
image: "rueda1208/controller"
version: "latest"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
init: false
startup: services
host_network: false
homeassistant_api: true
map:
  - type: share           # This maps Host: /share -> Container: /share
    read_only: false
environment:
  LOGLEVEL: INFO
  TZ: America/Montreal
options:
  gdp_events:
    date: "2025-12-01"
    plage: "AM/PM"     # AM, PM, AM/PM
schema:
  gdp_events:
    date: str
    plage: str